using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace csharp_test_client
{
    class PacketDef
    {
        public const Int16 PACKET_HEADER_SIZE = 5;
        public const int MAX_USER_ID_BYTE_LENGTH = 16;
        public const int MAX_USER_PW_BYTE_LENGTH = 16;
        public const int DEV_ECHO_DATA_MAX_SIZE = 1024;
    }

    public enum PACKET_ID : ushort
    {
        // 로그인
        LOGIN_REQ = 21,
        LOGIN_RES = 22,

        LOBBY_LIST_REQ = 26,
        LOBBY_LIST_RES = 27,

        LOBBY_ENTER_REQ = 31,
        LOBBY_ENTER_RES = 32,

        LOBBY_LEAVE_REQ = 46,
        LOBBY_LEAVE_RES = 47,
        
        ROOM_ENTER_REQ = 61,
        ROOM_ENTER_RES = 62,        
        ROOM_NEW_USER_NTF = 63,
        ROOM_USER_LIST_NTF = 64,

        ROOM_LEAVE_REQ = 66,
        ROOM_LEAVE_RES = 67,
        ROOM_LEAVE_USER_NTF = 68,

        ROOM_CHAT_REQ = 76,
        ROOM_CHAT_RES = 77,
        ROOM_CHAT_NOTIFY = 78,


        DEV_ECHO_REQ = 241,
        DEV_ECHO_RES = 242,

        //PACKET_ID_ERROR_NTF = 703,

        // Ping(Heart-beat)
        //PING_REQ = 706,
        //PING_RES = 707,

        //PACKET_ID_ROOM_RELAY_REQ = 741,
        //PACKET_ID_ROOM_RELAY_NTF = 742,
    }


    public enum ERROR_CODE : Int16
    {
        ERROR_NONE = 0,


        ERROR_CODE_USER_MGR_INVALID_USER_UNIQUEID = 112,

        ERROR_CODE_PUBLIC_CHANNEL_IN_USER = 114,

        ERROR_CODE_PUBLIC_CHANNEL_INVALIDE_NUMBER = 115,



        UNASSIGNED_ERROR = 201,

        MAIN_INIT_NETWORK_INIT_FAIL = 206,

        USER_MGR_ID_DUPLICATION = 211,
        USER_MGR_MAX_USER_COUNT = 212,
        USER_MGR_INVALID_SESSION_INDEX = 213,
        USER_MGR_NOT_CONFIRM_USER = 214,
        USER_MGR_REMOVE_INVALID_SESSION = 221,
        USER_MGR_WRONG_PASSWORD = 222,
        USER_MGR_ALREADY_LOGIN = 223,

        LOBBY_LIST_INVALID_DOMAIN = 226,

        LOBBY_ENTER_INVALID_DOMAIN = 231,
        LOBBY_ENTER_INVALID_LOBBY_INDEX = 232,
        LOBBY_ENTER_USER_DUPLICATION = 234,
        LOBBY_ENTER_MAX_USER_COUNT = 235,
        LOBBY_ENTER_EMPTY_USER_LIST = 236,

        LOBBY_ROOM_LIST_INVALID_START_ROOM_INDEX = 241,
        LOBBY_ROOM_LIST_INVALID_DOMAIN = 242,
        LOBBY_ROOM_LIST_INVALID_LOBBY_INDEX = 243,

        LOBBY_USER_LIST_INVALID_DOMAIN = 251,
        LOBBY_USER_LIST_INVALID_LOBBY_INDEX = 252,
        LOBBY_USER_LIST_INVALID_START_USER_INDEX = 253,

        LOBBY_LEAVE_INVALID_DOMAIN = 261,
        LOBBY_LEAVE_INVALID_LOBBY_INDEX = 262,
        LOBBY_LEAVE_USER_NVALID_UNIQUEINDEX = 263,

        ROOM_ENTER_INVALID_DOMAIN = 271,
        ROOM_ENTER_INVALID_LOBBY_INDEX = 272,
        ROOM_ENTER_INVALID_ROOM_INDEX = 273,
        ROOM_ENTER_CREATE_FAIL = 274,
        ROOM_ENTER_NOT_CREATED = 275,
        ROOM_ENTER_MEMBER_FULL = 276,
        ROOM_ENTER_EMPTY_ROOM = 277,


        ROOM_LEAVE_INVALID_DOMAIN = 286,
        ROOM_LEAVE_INVALID_LOBBY_INDEX = 287,
        ROOM_LEAVE_INVALID_ROOM_INDEX = 288,
        ROOM_LEAVE_NOT_CREATED = 289,
        ROOM_LEAVE_NOT_MEMBER = 290,

        ROOM_CHAT_INVALID_DOMAIN = 296,
        ROOM_CHAT_INVALID_LOBBY_INDEX = 297,
        ROOM_CHAT_INVALID_ROOM_INDEX = 298,

        LOBBY_CHAT_INVALID_DOMAIN = 306,
        LOBBY_CHAT_INVALID_LOBBY_INDEX = 307,

        ROOM_MASTER_GAME_START_INVALID_DOMAIN = 401,
        ROOM_MASTER_GAME_START_INVALID_LOBBY_INDEX = 402,
        ROOM_MASTER_GAME_START_INVALID_ROOM_INDEX = 403,
        ROOM_MASTER_GAME_START_INVALID_MASTER = 404,
        ROOM_MASTER_GAME_START_INVALID_GAME_STATE = 405,
        ROOM_MASTER_GAME_START_INVALID_USER_COUNT = 406,
    }
}
